name: Build & Test Python Bindings

on:
  push:      # any branch
  pull_request:
    branches: [ main, dev ]

jobs:
  build-test-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout FastLanes
        uses: actions/checkout@v4

      - name: Set up system Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build & Test via Makefile
        run: |
          make rebuild_python
          make test_python
